artifact_location: file:D:/cella/Cellaa/pijak/SMSML_Marcella-Fitri-Handayani/Workflow-CI/MLProject/ml/165463346566474441
creation_time: 1780652562096
effective_trace_archival_retention: null
experiment_id: '165463346566474441'
last_update_time: 1780652562096
lifecycle_stage: active
name: Bank_Fraud_Baseline
trace_location: null
workspace: default
